version: 1.0.{build}
image: Visual Studio 2017
configuration:
  - Release
platform: Any CPU
shallow_clone: true
before_build:
  - nuget restore
build:
  project: NotLiteCode.sln
  parallel: true
  verbosity: minimal
after_build:
  - nuget pack NotLiteCode\NotLiteCode.nuspec
  - nuget pack NotLiteCode.Serialization.GroBuf\NotLiteCode.Serialization.GroBuf.nuspec
deploy:
  provider: NuGet
  api_key:
    secure: 0wQtlbJ3suan1cUNWBFvnETONTJY7kXKJqH7sDsd+bE4znfjyO7FPiMlVnbUMa9n
  artifact: NLC-Package
artifacts:
  - path: '*.nupkg'
    name: NLC-Package
    type: NuGetPackage
