version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Release
platform: Any CPU
shallow_clone: true
build:
  project: NotLiteCode.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: NotLiteCode\bin\Release\NotLiteCode.dll
  name: NotLiteCode.dll
